version: '3.8'
services:
  hospital-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - hospital-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hospital-db:3306/hospitaldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  hospital-db:
    image: mysql:8.0
    container_name: hospital-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospitaldb
    ports:
      - "3306:3306"
    volumes:
      - hospital-data:/var/lib/mysql

volumes:
  hospital-data:
